apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-guest-book
  namespace: openshift-gitops
spec:
  destination:
    namespace: guest-book
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: app
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true