

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../bases
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
patches:
  - path: patch-console-link.yaml
    target:
      kind: ConsoleLink